### PR TITLE
Merge Minimal Viable Product to Main

### PR DESCRIPTION
**Pull request by davleop**

### CODE REVIEW

**Comment by davleop** [comment]
@prescient-slime If you could review this sometime this weekend, we could get this merged!

**Review by davleop — COMMENTED** [review]
:+1:

**Review by prescient-slime — APPROVED** [review]
Looks good to me. I'll submit a merge tonight

**Review by davleop — COMMENTED** [review]
:+1:

**Review by prescient-slime — APPROVED** [review]
finished review

**Pull request merged**
